### ISSUE TITLE
error: undefined reference to 'frexpl'

### ISSUE THREAD

**Issue by pichurriaj** [PICHURRIAJUEGOS-/muruby#5]
error: undefined reference to 'frexpl'
al compilar para android,
se prueba tanto para ndk-r9 y ndk-r10d

**Comment by Moon4u** [comment]
I thinkg frexpl is a math.h function that doesn't exist in the android library. The function frexp is supposed to be used instead.

**Comment by pichurriaj** [comment]
that's right, i found somthing about ndk/sources/android/support

**Comment by pichurriaj** [comment]
the cause
https://github.com/mruby/mruby/pull/2723
 re-implement mrb_float_to_str() #2723
